- name: Deploy Docker Container
  hosts: targets
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker Image from Docker Hub
      command: docker pull basma227/flask-weather-app:latest

    - name: Remove existing container (if exists)
      command: docker rm -f weather-container
      ignore_errors: yes

    - name: Create database directory on host
      file:
        path: /home/vagrant/data
        state: directory
        mode: '0777'

    - name: Run Docker Container with Volume
      command: docker run -d --name weather-container -p 8080:80 -v /home/vagrant/data:/app/data basma227/flask-weather-app:latest
